version: '3.1'
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: mysql:5.7
    container_name: dbmysql
    command: --default-authentication-plugin=mysql_native_password 
    volumes:
      - ./mysql/db-with-dummy-data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: tester
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user_pass'
    ports:
      - "3306:3306"
    networks:
      - default
    
  phpadmin:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

