version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: dbmysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: tester
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - "3306:3306"
    
  phpadmin:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
